services:
  - type: web
    name: doc-forge-mock
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
