services:
  - type: web
    name: docforge-mock
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
