openapi: 3.0.1
info:
  title: Doc Forge Mock API
  description: API mock para simular el servicio de generación de documentos
  version: '1.0'
servers:
  - url: http://localhost:3030
    description: Local development server
paths:
  /api/v1/templates:
    get:
      summary: Obtener todos los templates
      tags:
        - Templates
      responses:
        '200':
          description: Lista de templates disponibles
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      templates:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: "xxxx-xxxx-xxxx-xxxx"
                            name:
                              type: string
                              example: "Template 1"
                            description:
                              type: string
                              example: "Template 1 description"
                            gdrive_id:
                              type: string
                              example: "xxxx-xxxx-xxxx-xxxx"
                            documents:
                              type: array
                              items:
                                type: object
                                properties:
                                  document_type:
                                    type: string
                                    example: "CC"
                                  fields:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        name:
                                          type: string
                                          example: "Field 1"
                                        description:
                                          type: string
                                          example: "Field 1 description"
                                        required:
                                          type: boolean
                                          example: true
  /api/v1/documents/types:
    get:
      summary: Obtener tipos de documentos
      tags:
        - Documents
      responses:
        '200':
          description: Lista de tipos de documentos disponibles
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      types:
                        type: array
                        items:
                          type: string
  /api/v1/documents/process:
    post:
      summary: Procesar documento
      tags:
        - Documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                template_id:
                  type: string
                  example: "xxxx-xxxx-xxxx-xxxx"
                uploaded_files:
                  type: array
                  items:
                    type: object
                    properties:
                      document_type:
                        type: string
                        example: "CC"
                      base64:
                        type: string
                        example: "as...=="
                      file_name:
                        type: string
                        example: "test.pdf"
      responses:
        '200':
          description: Documento procesado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      type: object
                      properties:
                        document_type:
                          type: string
                          example: "CC"
                        fields:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: "Field 1"
                              value:
                                type: string
                                example: "Value 1"
  /api/v1/documents/generate:
    post:
      summary: Generar documento
      tags:
        - Documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                template_id:
                  type: string
                  example: "xxxx-xxxx-xxxx-xxxx"
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "Field 1"
                      value:
                        type: string
                        example: "Value 1"
      responses:
        '200':
          description: Documento generado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated_document:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "generated.pdf"
                      gdrive_id:
                        type: string
                        example: "xxxx-xxxx-xxxx-xxxx"
                      url:
                        type: string
                        example: "https://www.google.com"
  /api/v1/documents/{gdrive_id}/download:
    get:
      summary: Descargar documento
      tags:
        - Documents
      parameters:
        - name: gdrive_id
          in: path
          required: true
          schema:
            type: string
            example: "xxxx-xxxx-xxxx-xxxx"
      responses:
        '200':
          description: Documento descargado exitosamente
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/pdf"
            Content-Disposition:
              schema:
                type: string
                example: "attachment; filename=document.pdf"
          content:
            application/pdf:
              schema:
                type: string
                format: binary
